site_name: Documentation Spot in
site_url: https://docsspotinch.netlify.app/

nav:
  - index.md
  - spot.md
  - spot-programmable.md
  - perennite.md
  - ethique.md
  - utilisations.md
  - hugo.md
  - api.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.superfences

plugins: 
  - social

theme:
  favicon: assets/favicon.png
  font: none
  language: fr
  logo: assets/logo.png
  name: material
  palette: 
    primary: white