site_name: Spot in Documentation
site_url: https://docsspotinch.netlify.app/

nav:
  - index.md
  - spot.md
  - programmable-spots.md
  - sustainability.md
  - ethics.md
  - type-of-uses.md
  - hugo.md
  - api.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.superfences

plugins: 
  - social
  - search

theme:
  favicon: assets/favicon.png
  font: none
  language: en
  logo: assets/logo.png
  name: material
  palette: 
    primary: white